### ISSUE TITLE
Polling should only occur in the proper context

### ISSUE THREAD

**Issue by contextlimit** [mobify/oculus.js#1]
When a handler is setup, it should be assigned to a certain view. When that view is not focused, the associated handlers should not be running. Their timeouts should be halted, and resumed when their view is back in focus. 

cc @Helen-Mobify

**Comment by wizardlyhel** [comment]
This idea here is that we don't want to be polling all the time because polling can become expensive.

Example: You have some polling on some elements and you trigger a pinny. In this case, pinny blocks those watching elements and there is no point to have polling happening while user is interacting with the pinny content.
